language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install coveralls
  - python setup.py install

# Run the nose framework to discover and run test classes
script:
  - coverage run --source=zonebot -m nose2.__main__ -v

after_success:
   - coveralls
