language: python
sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - travis_retry pip install -r requirements.txt

# Run the nose framework to discover and run test classes
script:
  - if [[ "${TRAVIS_PYTHON_VERSION}" != 3.2 ]]; then CMD="coverage run"; else CMD="python";
    fi; PYTHONPATH=. $CMD -m nose2.__main__ -v

after_success:
   - coveralls
